name: Docker Build & Push

on:
  workflow_call:
    inputs:
      image_name:
        description: "Full image name (e.g., ghcr.io/sushiibot/modmail)"
        required: true
        type: string
      dockerfile:
        description: "Path to Dockerfile"
        required: false
        default: "./Dockerfile"
        type: string
      context:
        description: "Docker build context"
        required: false
        default: "."
        type: string
      platforms:
        description: "Target platforms"
        required: false
        default: "linux/amd64,linux/arm64"
        type: string
      build_args:
        description: "Multiline build args"
        required: false
        default: ""
        type: string
    outputs:
      image_version:
        description: "Short git SHA used as image tag"
        value: ${{ jobs.build.outputs.image_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_version: ${{ steps.version.outputs.short_sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Set image version
        id: version
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Log in to ghcr.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ inputs.image_name }}:latest
            ${{ inputs.image_name }}:${{ steps.version.outputs.short_sha }}
          build-args: |
            GIT_HASH=${{ steps.version.outputs.short_sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            ${{ inputs.build_args }}
          cache-from: type=registry,ref=${{ inputs.image_name }}:buildcache
          cache-to: type=registry,ref=${{ inputs.image_name }}:buildcache,mode=max
